### ISSUE TITLE
Displayed 'Date Filed' on Case Law search page is confusing or wrong

### ISSUE THREAD

**Issue by grossir** [freelawproject/courtlistener#3785]
I think there is a bug in the display of Date Filed on the Case Law search page

For example, this [query](https://www.courtlistener.com/?q=court_id%3Atax&type=o&order_by=dateFiled%20asc&stat_Precedential=on&stat_Non-Precedential=on&filed_after=11/19/2020&filed_before=01/27/2022), which filters by `Filed After: 11/19/2020`, displays opinions with `Date Filed: November 18th, 2020` 

If one goes into [one](https://www.courtlistener.com/opinion/4832151/kumar-rajagopalan-susamma-kumar-v-commissioner/?q=court_id%3Atax&type=o&order_by=dateFiled%20asc&stat_Precedential=on&stat_Non-Precedential=on&filed_after=11/19/2020&filed_before=01/27/2022) of this opinions, it shows another date `Filed: November 19th, 2020`
![image](https://github.com/freelawproject/courtlistener/assets/14970769/3e08ab88-4d28-4cc5-ac12-3aa1e9bab3d2)

**Comment by mlissner** [comment]
@albertisfu, I'm embarrassed to say so, but I forget if we're using the new opinion search or not. I know we had timezone issues with Solr, but I think they're fixed in Elastic, no?

**Comment by albertisfu** [comment]
Yes, this seems to be an issue exclusive to Solr.

Here is how the same query appears in ES when authenticated in CL.

![Screenshot 2024-02-14 at 18 08 20](https://github.com/freelawproject/courtlistener/assets/486004/97b61130-9ad2-4ebe-8529-a41aad4d44e7)

ES Opinions Search is only enabled for staff users, while the public version continues to work with Solr. I believe we still have a blocker related to cleaning up Opinion Search Alerts before we can make the ES version available to the public.

**Comment by mlissner** [comment]
Great, thanks for filing, Alberto. Closing as dup of https://github.com/freelawproject/courtlistener/issues/864
